### ISSUE TITLE
version inconsistent problem

### ISSUE THREAD

**Issue by kennynaoh** [fooplugins/foonav#6]
Hello @steveush ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
The latest version in git tag is 0.0.1, but the version in ```package.json``` in master branch is 0.0.3.
Could you confirm that?
Thanks.

https://github.com/cdnjs/cdnjs/issues/7006
https://github.com/cdnjs/cdnjs/pull/7374

**Comment by PeterDaveHello** [comment]
Looks like tag for `v0.0.3` is missing, is this a version inconsistent problem? At least I didn't see version `0.0.3` in tag `v0.0.1`

**Comment by steveush** [comment]
Hi,

Apologies seems I missed the first notification for this issue. I've fixed the versioning issues, the actual version is 0.0.6 at the moment. I've updated the package.json, comments and the tag on the repo to reflect this.

Thanks

**Comment by PeterDaveHello** [comment]
Hi @steveush , is it possible to also tag the old versions as well? So that we can recognize and include all the versions, thanks.

**Comment by steveush** [comment]
Done

**Comment by PeterDaveHello** [comment]
Thank you very much @steveush
